name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Clonador
        run: pip install pywebcopy

      - name: Clonar Sitio Web
        run: |
          python -c "
          from pywebcopy import save_webpage
          url = 'https://web.archive.org/web/20250329232311/https://cabanaslosolivos.com.ar/'
          download_folder = './website-content/'
          kwargs = {'project_name': 'clon_olivos'}
          save_webpage(url, download_folder, **kwargs)
          "

      - name: Subir Archivos
        uses: actions/upload-artifact@v3
        with:
          name: sitio-clonado
          path: website-content/clon_olivos/
